# fly.toml app configuration file generated for snowy-dust-3589 on 2023-05-22T15:50:25+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snowy-dust-3589"
primary_region = "ewr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
